// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module router_regs (
        input wire clk,
        input wire rst,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [3:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input router_regs_pkg::router_regs__in_t hwif_in,
        output router_regs_pkg::router_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [3:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[3:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end
    assign cpuif_wr_biten = '1;

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic CHANNEL_ENABLE;
        logic MODE;
        logic PRIORITY;
        logic PACKET_COUNT;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.CHANNEL_ENABLE = cpuif_req_masked & (cpuif_addr == 4'h0);
        decoded_reg_strb.MODE = cpuif_req_masked & (cpuif_addr == 4'h4);
        decoded_reg_strb.PRIORITY = cpuif_req_masked & (cpuif_addr == 4'h8);
        decoded_reg_strb.PACKET_COUNT = cpuif_req_masked & (cpuif_addr == 4'hc);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [1:0] next;
                logic load_next;
            } ch0_en;
            struct {
                logic [1:0] next;
                logic load_next;
            } ch1_en;
            struct {
                logic [1:0] next;
                logic load_next;
            } ch2_en;
            struct {
                logic [1:0] next;
                logic load_next;
            } ch3_en;
        } CHANNEL_ENABLE;
        struct {
            struct {
                logic [1:0] next;
                logic load_next;
            } mode;
        } MODE;
        struct {
            struct {
                logic [1:0] next;
                logic load_next;
            } ch0_priority;
            struct {
                logic [1:0] next;
                logic load_next;
            } ch1_priority;
            struct {
                logic [1:0] next;
                logic load_next;
            } ch2_priority;
            struct {
                logic [1:0] next;
                logic load_next;
            } ch3_priority;
        } PRIORITY;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } ch0_count;
            struct {
                logic [7:0] next;
                logic load_next;
            } ch1_count;
            struct {
                logic [7:0] next;
                logic load_next;
            } ch2_count;
            struct {
                logic [7:0] next;
                logic load_next;
            } ch3_count;
        } PACKET_COUNT;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [1:0] value;
            } ch0_en;
            struct {
                logic [1:0] value;
            } ch1_en;
            struct {
                logic [1:0] value;
            } ch2_en;
            struct {
                logic [1:0] value;
            } ch3_en;
        } CHANNEL_ENABLE;
        struct {
            struct {
                logic [1:0] value;
            } mode;
        } MODE;
        struct {
            struct {
                logic [1:0] value;
            } ch0_priority;
            struct {
                logic [1:0] value;
            } ch1_priority;
            struct {
                logic [1:0] value;
            } ch2_priority;
            struct {
                logic [1:0] value;
            } ch3_priority;
        } PRIORITY;
        struct {
            struct {
                logic [7:0] value;
            } ch0_count;
            struct {
                logic [7:0] value;
            } ch1_count;
            struct {
                logic [7:0] value;
            } ch2_count;
            struct {
                logic [7:0] value;
            } ch3_count;
        } PACKET_COUNT;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: router_regs.CHANNEL_ENABLE.ch0_en
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CHANNEL_ENABLE.ch0_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.CHANNEL_ENABLE && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CHANNEL_ENABLE.ch0_en.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.CHANNEL_ENABLE.ch0_en.next = next_c;
        field_combo.CHANNEL_ENABLE.ch0_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CHANNEL_ENABLE.ch0_en.value <= 2'h0;
        end else begin
            if(field_combo.CHANNEL_ENABLE.ch0_en.load_next) begin
                field_storage.CHANNEL_ENABLE.ch0_en.value <= field_combo.CHANNEL_ENABLE.ch0_en.next;
            end
        end
    end
    assign hwif_out.CHANNEL_ENABLE.ch0_en.value = field_storage.CHANNEL_ENABLE.ch0_en.value;
    // Field: router_regs.CHANNEL_ENABLE.ch1_en
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CHANNEL_ENABLE.ch1_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.CHANNEL_ENABLE && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CHANNEL_ENABLE.ch1_en.value & ~decoded_wr_biten[3:2]) | (decoded_wr_data[3:2] & decoded_wr_biten[3:2]);
            load_next_c = '1;
        end
        field_combo.CHANNEL_ENABLE.ch1_en.next = next_c;
        field_combo.CHANNEL_ENABLE.ch1_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CHANNEL_ENABLE.ch1_en.value <= 2'h1;
        end else begin
            if(field_combo.CHANNEL_ENABLE.ch1_en.load_next) begin
                field_storage.CHANNEL_ENABLE.ch1_en.value <= field_combo.CHANNEL_ENABLE.ch1_en.next;
            end
        end
    end
    assign hwif_out.CHANNEL_ENABLE.ch1_en.value = field_storage.CHANNEL_ENABLE.ch1_en.value;
    // Field: router_regs.CHANNEL_ENABLE.ch2_en
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CHANNEL_ENABLE.ch2_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.CHANNEL_ENABLE && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CHANNEL_ENABLE.ch2_en.value & ~decoded_wr_biten[5:4]) | (decoded_wr_data[5:4] & decoded_wr_biten[5:4]);
            load_next_c = '1;
        end
        field_combo.CHANNEL_ENABLE.ch2_en.next = next_c;
        field_combo.CHANNEL_ENABLE.ch2_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CHANNEL_ENABLE.ch2_en.value <= 2'h2;
        end else begin
            if(field_combo.CHANNEL_ENABLE.ch2_en.load_next) begin
                field_storage.CHANNEL_ENABLE.ch2_en.value <= field_combo.CHANNEL_ENABLE.ch2_en.next;
            end
        end
    end
    assign hwif_out.CHANNEL_ENABLE.ch2_en.value = field_storage.CHANNEL_ENABLE.ch2_en.value;
    // Field: router_regs.CHANNEL_ENABLE.ch3_en
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CHANNEL_ENABLE.ch3_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.CHANNEL_ENABLE && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CHANNEL_ENABLE.ch3_en.value & ~decoded_wr_biten[7:6]) | (decoded_wr_data[7:6] & decoded_wr_biten[7:6]);
            load_next_c = '1;
        end
        field_combo.CHANNEL_ENABLE.ch3_en.next = next_c;
        field_combo.CHANNEL_ENABLE.ch3_en.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CHANNEL_ENABLE.ch3_en.value <= 2'h3;
        end else begin
            if(field_combo.CHANNEL_ENABLE.ch3_en.load_next) begin
                field_storage.CHANNEL_ENABLE.ch3_en.value <= field_combo.CHANNEL_ENABLE.ch3_en.next;
            end
        end
    end
    assign hwif_out.CHANNEL_ENABLE.ch3_en.value = field_storage.CHANNEL_ENABLE.ch3_en.value;
    // Field: router_regs.MODE.mode
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.MODE.mode.value;
        load_next_c = '0;
        if(decoded_reg_strb.MODE && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.MODE.mode.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.MODE.mode.next = next_c;
        field_combo.MODE.mode.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.MODE.mode.value <= 2'h0;
        end else begin
            if(field_combo.MODE.mode.load_next) begin
                field_storage.MODE.mode.value <= field_combo.MODE.mode.next;
            end
        end
    end
    assign hwif_out.MODE.mode.value = field_storage.MODE.mode.value;
    // Field: router_regs.PRIORITY.ch0_priority
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PRIORITY.ch0_priority.value;
        load_next_c = '0;
        if(decoded_reg_strb.PRIORITY && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PRIORITY.ch0_priority.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.PRIORITY.ch0_priority.next = next_c;
        field_combo.PRIORITY.ch0_priority.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PRIORITY.ch0_priority.value <= 2'h0;
        end else begin
            if(field_combo.PRIORITY.ch0_priority.load_next) begin
                field_storage.PRIORITY.ch0_priority.value <= field_combo.PRIORITY.ch0_priority.next;
            end
        end
    end
    assign hwif_out.PRIORITY.ch0_priority.value = field_storage.PRIORITY.ch0_priority.value;
    // Field: router_regs.PRIORITY.ch1_priority
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PRIORITY.ch1_priority.value;
        load_next_c = '0;
        if(decoded_reg_strb.PRIORITY && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PRIORITY.ch1_priority.value & ~decoded_wr_biten[3:2]) | (decoded_wr_data[3:2] & decoded_wr_biten[3:2]);
            load_next_c = '1;
        end
        field_combo.PRIORITY.ch1_priority.next = next_c;
        field_combo.PRIORITY.ch1_priority.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PRIORITY.ch1_priority.value <= 2'h0;
        end else begin
            if(field_combo.PRIORITY.ch1_priority.load_next) begin
                field_storage.PRIORITY.ch1_priority.value <= field_combo.PRIORITY.ch1_priority.next;
            end
        end
    end
    assign hwif_out.PRIORITY.ch1_priority.value = field_storage.PRIORITY.ch1_priority.value;
    // Field: router_regs.PRIORITY.ch2_priority
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PRIORITY.ch2_priority.value;
        load_next_c = '0;
        if(decoded_reg_strb.PRIORITY && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PRIORITY.ch2_priority.value & ~decoded_wr_biten[5:4]) | (decoded_wr_data[5:4] & decoded_wr_biten[5:4]);
            load_next_c = '1;
        end
        field_combo.PRIORITY.ch2_priority.next = next_c;
        field_combo.PRIORITY.ch2_priority.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PRIORITY.ch2_priority.value <= 2'h0;
        end else begin
            if(field_combo.PRIORITY.ch2_priority.load_next) begin
                field_storage.PRIORITY.ch2_priority.value <= field_combo.PRIORITY.ch2_priority.next;
            end
        end
    end
    assign hwif_out.PRIORITY.ch2_priority.value = field_storage.PRIORITY.ch2_priority.value;
    // Field: router_regs.PRIORITY.ch3_priority
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PRIORITY.ch3_priority.value;
        load_next_c = '0;
        if(decoded_reg_strb.PRIORITY && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.PRIORITY.ch3_priority.value & ~decoded_wr_biten[7:6]) | (decoded_wr_data[7:6] & decoded_wr_biten[7:6]);
            load_next_c = '1;
        end
        field_combo.PRIORITY.ch3_priority.next = next_c;
        field_combo.PRIORITY.ch3_priority.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PRIORITY.ch3_priority.value <= 2'h0;
        end else begin
            if(field_combo.PRIORITY.ch3_priority.load_next) begin
                field_storage.PRIORITY.ch3_priority.value <= field_combo.PRIORITY.ch3_priority.next;
            end
        end
    end
    assign hwif_out.PRIORITY.ch3_priority.value = field_storage.PRIORITY.ch3_priority.value;
    // Field: router_regs.PACKET_COUNT.ch0_count
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PACKET_COUNT.ch0_count.value;
        load_next_c = '0;
        
        // HW Write
        next_c = hwif_in.PACKET_COUNT.ch0_count.next;
        load_next_c = '1;
        field_combo.PACKET_COUNT.ch0_count.next = next_c;
        field_combo.PACKET_COUNT.ch0_count.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PACKET_COUNT.ch0_count.value <= 8'h0;
        end else begin
            if(field_combo.PACKET_COUNT.ch0_count.load_next) begin
                field_storage.PACKET_COUNT.ch0_count.value <= field_combo.PACKET_COUNT.ch0_count.next;
            end
        end
    end
    assign hwif_out.PACKET_COUNT.ch0_count.value = field_storage.PACKET_COUNT.ch0_count.value;
    // Field: router_regs.PACKET_COUNT.ch1_count
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PACKET_COUNT.ch1_count.value;
        load_next_c = '0;
        
        // HW Write
        next_c = hwif_in.PACKET_COUNT.ch1_count.next;
        load_next_c = '1;
        field_combo.PACKET_COUNT.ch1_count.next = next_c;
        field_combo.PACKET_COUNT.ch1_count.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PACKET_COUNT.ch1_count.value <= 8'h8;
        end else begin
            if(field_combo.PACKET_COUNT.ch1_count.load_next) begin
                field_storage.PACKET_COUNT.ch1_count.value <= field_combo.PACKET_COUNT.ch1_count.next;
            end
        end
    end
    assign hwif_out.PACKET_COUNT.ch1_count.value = field_storage.PACKET_COUNT.ch1_count.value;
    // Field: router_regs.PACKET_COUNT.ch2_count
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PACKET_COUNT.ch2_count.value;
        load_next_c = '0;
        
        // HW Write
        next_c = hwif_in.PACKET_COUNT.ch2_count.next;
        load_next_c = '1;
        field_combo.PACKET_COUNT.ch2_count.next = next_c;
        field_combo.PACKET_COUNT.ch2_count.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PACKET_COUNT.ch2_count.value <= 8'h10;
        end else begin
            if(field_combo.PACKET_COUNT.ch2_count.load_next) begin
                field_storage.PACKET_COUNT.ch2_count.value <= field_combo.PACKET_COUNT.ch2_count.next;
            end
        end
    end
    assign hwif_out.PACKET_COUNT.ch2_count.value = field_storage.PACKET_COUNT.ch2_count.value;
    // Field: router_regs.PACKET_COUNT.ch3_count
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.PACKET_COUNT.ch3_count.value;
        load_next_c = '0;
        
        // HW Write
        next_c = hwif_in.PACKET_COUNT.ch3_count.next;
        load_next_c = '1;
        field_combo.PACKET_COUNT.ch3_count.next = next_c;
        field_combo.PACKET_COUNT.ch3_count.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.PACKET_COUNT.ch3_count.value <= 8'h18;
        end else begin
            if(field_combo.PACKET_COUNT.ch3_count.load_next) begin
                field_storage.PACKET_COUNT.ch3_count.value <= field_combo.PACKET_COUNT.ch3_count.next;
            end
        end
    end
    assign hwif_out.PACKET_COUNT.ch3_count.value = field_storage.PACKET_COUNT.ch3_count.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[4];
    assign readback_array[0][1:0] = (decoded_reg_strb.CHANNEL_ENABLE && !decoded_req_is_wr) ? field_storage.CHANNEL_ENABLE.ch0_en.value : '0;
    assign readback_array[0][3:2] = (decoded_reg_strb.CHANNEL_ENABLE && !decoded_req_is_wr) ? field_storage.CHANNEL_ENABLE.ch1_en.value : '0;
    assign readback_array[0][5:4] = (decoded_reg_strb.CHANNEL_ENABLE && !decoded_req_is_wr) ? field_storage.CHANNEL_ENABLE.ch2_en.value : '0;
    assign readback_array[0][7:6] = (decoded_reg_strb.CHANNEL_ENABLE && !decoded_req_is_wr) ? field_storage.CHANNEL_ENABLE.ch3_en.value : '0;
    assign readback_array[0][31:8] = '0;
    assign readback_array[1][1:0] = (decoded_reg_strb.MODE && !decoded_req_is_wr) ? field_storage.MODE.mode.value : '0;
    assign readback_array[1][31:2] = '0;
    assign readback_array[2][1:0] = (decoded_reg_strb.PRIORITY && !decoded_req_is_wr) ? field_storage.PRIORITY.ch0_priority.value : '0;
    assign readback_array[2][3:2] = (decoded_reg_strb.PRIORITY && !decoded_req_is_wr) ? field_storage.PRIORITY.ch1_priority.value : '0;
    assign readback_array[2][5:4] = (decoded_reg_strb.PRIORITY && !decoded_req_is_wr) ? field_storage.PRIORITY.ch2_priority.value : '0;
    assign readback_array[2][7:6] = (decoded_reg_strb.PRIORITY && !decoded_req_is_wr) ? field_storage.PRIORITY.ch3_priority.value : '0;
    assign readback_array[2][31:8] = '0;
    assign readback_array[3][7:0] = (decoded_reg_strb.PACKET_COUNT && !decoded_req_is_wr) ? field_storage.PACKET_COUNT.ch0_count.value : '0;
    assign readback_array[3][15:8] = (decoded_reg_strb.PACKET_COUNT && !decoded_req_is_wr) ? field_storage.PACKET_COUNT.ch1_count.value : '0;
    assign readback_array[3][23:16] = (decoded_reg_strb.PACKET_COUNT && !decoded_req_is_wr) ? field_storage.PACKET_COUNT.ch2_count.value : '0;
    assign readback_array[3][31:24] = (decoded_reg_strb.PACKET_COUNT && !decoded_req_is_wr) ? field_storage.PACKET_COUNT.ch3_count.value : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<4; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
